package constants

// 日志模板集中定义：所有 handler / service / middleware 必须通过 util/logger.go
// 引用这些模板，禁止在业务代码中手写散落的日志字符串。
// 注意：业务字段或枚举变更时，必须同步修改对应日志模板与调用处（牵一发动全身）。
const (
	// 通用
	LogServerStarting = "在线考试系统服务启动中，端口=%s"
	LogServerStarted  = "在线考试系统服务已启动，监听地址=%s"
	LogServerShutdown = "在线考试系统服务正在关闭"
	LogRequestHandled = "请求处理完成 request_id=%s method=%s path=%s status=%d latency_ms=%d"
	LogRequestFailed  = "请求处理失败 request_id=%s method=%s path=%s error=%s"
	LogPanicRecovered = "请求发生 panic 已恢复 request_id=%s path=%s panic=%v"

	// 用户模块（角色枚举 RoleAdmin/RoleTeacher/RoleStudent）
	LogUserRegistered    = "用户注册成功 role=%s email=%s"
	LogUserLogin         = "用户登录成功 role=%s email=%s"
	LogUserLoginFailed   = "用户登录失败 role=%s email=%s error=%s"
	LogUserCreated       = "管理员创建用户 role=%s email=%s operator=%s"
	LogUserUpdated       = "用户信息更新 role=%s email=%s operator=%s"
	LogUserDeleted       = "用户删除 email=%s operator=%s"
	LogUserPasswordReset = "用户密码重置 email=%s operator=%s"

	// 题库模块（题型枚举 single/multiple/judge/fill/short，难度 easy/medium/hard）
	LogQuestionCreated  = "题目创建成功 type=%s difficulty=%s subject=%s creator=%s"
	LogQuestionUpdated  = "题目更新 type=%s difficulty=%s subject=%s operator=%s"
	LogQuestionDeleted  = "题目删除 question_id=%s operator=%s"
	LogQuestionImported = "题目批量导入完成 count=%d subject=%s operator=%s"

	// 试卷模块（状态机 draft/published/ongoing/finished/closed）
	LogExamCreated       = "试卷创建成功 title=%s total_score=%d subject=%s creator=%s"
	LogExamAutoGenerated = "试卷自动组卷完成 title=%s question_count=%d difficulty=%s creator=%s"
	LogExamPublishSuccess = "试卷发布成功 exam_id=%s operator=%s"
	LogExamStatusChanged = "试卷状态流转 from=%s to=%s exam_id=%s operator=%s"
	LogExamUpdated       = "试卷更新 title=%s exam_id=%s operator=%s"
	LogExamDeleted       = "试卷删除 exam_id=%s operator=%s"

	// 考试记录模块（记录状态 in_progress/submitted/graded，结果 correct/wrong/partial/unmarked）
	LogRecordStarted    = "学生开始考试 record_id=%s exam_id=%s student=%s"
	LogRecordSubmitted  = "学生提交答卷 record_id=%s status=%s objective_score=%d student=%s"
	LogRecordAutoSubmit = "系统自动提交超时答卷 record_id=%s exam_id=%s student=%s"
	LogRecordGraded     = "教师批改主观题完成 record_id=%s result=%s final_score=%d teacher=%s"
	LogRecordCheat      = "检测到切屏行为 record_id=%s cheat_count=%d student=%s"

	// 错题本模块
	LogWrongBookAdded    = "错题加入错题本 student=%s question_id=%s"
	LogWrongBookResolved = "错题标记为已掌握 student=%s question_id=%s"

	// 审计模块
	LogAuditCreated = "审计日志写入成功 module=%s action=%s user=%s"
)
